// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Desc string  `json:"desc"`
	Date *string `json:"date,omitempty"`
}

type Order struct {
	ID   string  `json:"id"`
	Desc string  `json:"desc"`
	Date *string `json:"date,omitempty"`
}

type Query struct {
}
